#!/bin/sh

echo "Starting libnotificationde..."
ldid -s /var/jb/usr/libexec/libnotificationde /var/jb/usr/libexec/libnotificationde
ldid -s /var/jb/usr/lib/libnotifications.dylib /var/jb/usr/lib/libnotifications.dylib

chown root:wheel /var/jb/usr/libexec/libnotificationde
chmod 06777 /var/jb/usr/libexec/libnotificationde
chown root:wheel /var/jb/Library/LaunchDaemons/com.cokepokes.libnotificationde.plist
chmod 644 /var/jb/Library/LaunchDaemons/com.cokepokes.libnotificationde.plist
launchctl load /var/jb/Library/LaunchDaemons/com.cokepokes.libnotificationde.plist 2> /dev/null
echo "Done!"

exit 0
